server.port: 8090

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  datasource:
    platform: h2
    initialization-mode: never
logging:
  level:
    org.hibernate.SQL: DEBUG
